Enemy pursue logic and corpse template when died
gabriel654165/Very-Good-Cop pull request #12
Opened 2023-05-08 12:07 UTC by smbss1

2023-05-09 00:39 UTC, edouard-sn requested changes
quick review

2023-05-09 00:39 UTC, edouard-sn commented on scripts/Character/Enemy.gd
>  		#display le sprite au sol
French

2023-05-09 00:39 UTC, edouard-sn commented on scripts/Character/Enemy.gd
> +		var spriteDeadEnemy = spawn(corpse_prefab, self.global_position)
sprite_dead_enemy

2023-05-09 00:39 UTC, edouard-sn commented on scripts/Character/Enemy.gd
> -@onready var spriteDead: Sprite2D = $SpriteDead
sprite_dead

2023-05-09 00:39 UTC, edouard-sn commented on scripts/AI/States/Pursue.gd
> +		print("stop tween")
```suggestion
```

2023-05-09 04:05 UTC, gabriel654165 reviewed
Except naming good job !

2023-05-09 04:05 UTC, gabriel654165 commented on scripts/AI/States/Pursue.gd
> +extends AIState
Naming file

2023-05-09 04:05 UTC, gabriel654165 commented on scripts/AI/States/Pursue.gd
> +		set_movement_target(state_machine._enemy.global_transform.origin + target_move_direction * 500)
*500 is the distance he will look for the player ? the one he is going to walk for ?
If it is, it should be a parameter please.

2023-05-16 08:29 UTC, gabriel654165 approved these changes

2023-05-16 08:29 UTC, gabriel654165 commented on scripts/AI/States/GoToAndLookAround.gd
> +	tween = get_tree().create_tween()
quand tu nous avait montré les tween de l'enemy qui look around, il y avait bien un tween de rotation quand il regardais a gauche ou a droite mais il revenais au centre abruptement tu vois ce que je veux dire ? Est ce que c'est tjr le cas ? Si oui tu pourrait juste modifier le tween ? Sinon c'est bon !

2023-05-17 03:16 UTC, merged